import Banner from '@/components/Banner'
import ProductCart from '@/components/cards/ProductCart'
import Head from 'next/head'

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>AnimeCart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Banner />
        <div className='my-2 bg-light'><h4 className='text-center p-2 text-uppercase navbar-top-bg text-white'>Products</h4></div>
        <div className='row'>
          {
            products && products.map((item)=>{
              return(
                <div key={item.id} className='col-md-3 mt-4'><ProductCart product={item}/></div>
              )
            })
          }
        </div>
      </main>
    </>
  )
}


// Products listing using getServerSideProps for home page
export async function getServerSideProps(context) {
  let products = []
  try {
    const responce = await fetch('https://dummyjson.com/products');
    const result = await responce.json();
    products = result.products;
  } catch (error) {
    console.error(error)
    return { notFound: true }
  }

  return {
    props: {
      products
    }
  }
}